### ISSUE TITLE
feature request: compatibility with knative (or other scale-to-zero deployment models)

### ISSUE THREAD

**Issue by NickCao** [argoproj-labs/argocd-image-updater#187]
**Is your feature request related to a problem? Please describe.**
When trying to update images referenced in knative services, I found lines complaining "Image foo seems not to be live in this application, skipping" in debug log. Only when the given service happens to be active when the update kicks in, it will be considered live. And I found [`GetImagesFromApplication`](https://github.com/argoproj-labs/argocd-image-updater/blob/f1cc8e4542b0531f66fc5546f7467833b1d08ebe/pkg/argocd/argocd.go#L411-L421) to be the primary cause, as application.status.summary.images only contains images that are currently running.

**Describe the solution you'd like**
Add an annotation `argocd-image-updater.argoproj.io/<image_alias>.no-check`, so that the specified image is always updated whether it's live or not.

**Describe alternatives you've considered**
Or we can rework the `GetImagesFromApplication` logic so that it relies on spec rather than status, but that would require too much effort.

**Additional context**
A quick demo of the situation.
![Screenshot from 2021-04-09 11-44-45](https://user-images.githubusercontent.com/15247171/114125414-00bc9580-9929-11eb-9329-023521cc272b.png)

**Comment by jannfis** [comment]
Hi @NickCao, this is indeed an interesting scenario, thank you for bringing it up.

I think an additional annotation, such as you proposed, would be possible. I think it should not be `argocd-image-updater.argoproj.io/<image_alias>.no-check` however, but maybe rather something along `argocd-image-updater.argoproj.io/<image_alias>.force-update`.

As you correctly pointed out, the second option will be difficult to implement on the Image Updater side, because we're piggy-backing on Argo CD here. One of the major goals for Image Updater is to have only very limited permissions on the cluster, and perform all more privileged operations as well as information gathering through Argo CD. So basically this would require a change to Argo CD, to list the images found in the *desired* manifests instead of in the *live* manifests. But certainly, might be something to consider while going forward.

**Comment by iamnoah** [comment]
I need this feature so I'm working on it now 😀

**Comment by NickCao** [comment]
Tested #189 personally for several days, and it worked like a charm, guess we can safely close this now.
