### ISSUE TITLE
Metric for registry errors

### ISSUE THREAD

**Issue by janpieper-gcx** [argoproj-labs/argocd-image-updater#314]
**Is your feature request related to a problem? Please describe.**

The documentation lists `argocd_image_updater_registry_errors_total` and this metrics is used in the example Grafana dashboard, but it is not implemented.

**Describe the solution you'd like**

Implement the metric.

**Describe alternatives you've considered**

Maybe it was implemented in the past and removed for some reason, but couldn't find any information about that.

**Additional context**

https://github.com/argoproj-labs/argocd-image-updater/blob/da58411eea9f98811f55cc10b92c150385e2d9ae/docs/install/start.md#L309

https://github.com/argoproj-labs/argocd-image-updater/blob/da58411eea9f98811f55cc10b92c150385e2d9ae/config/example-grafana-dashboard.json#L518

**Comment by pacoguzman** [comment]
Working on this as my `first issue`

**Comment by pacoguzman** [comment]
I've just found that metric is already implemented

https://github.com/argoproj-labs/argocd-image-updater/blob/7ed1f675ca2373dd8f0442e1a398e3fc9a227c55/pkg/metrics/metrics.go#L158-L161

https://github.com/argoproj-labs/argocd-image-updater/blob/7ed1f675ca2373dd8f0442e1a398e3fc9a227c55/cmd/run.go#L322

is the confusion due to the naming?

**Comment by pacoguzman** [comment]
Opps sorry my fault the definition for that metric is here

https://github.com/argoproj-labs/argocd-image-updater/blob/7ed1f675ca2373dd8f0442e1a398e3fc9a227c55/pkg/metrics/metrics.go#L85-L88

And that metric is not what you pointed out.

So forget about this I'll keep looking

**Comment by jannfis** [comment]
Closed by #362
