### ISSUE TITLE
Helm chart to deploy argocd-image-updater

### ISSUE THREAD

**Issue by 0m1xa** [argoproj-labs/argocd-image-updater#382]
**Is your feature request related to a problem? Please describe.**
Currently I have to download manifests for argocd-image-updater, modify them and only then apply if I need some customization. I don't see any other way to deploy it in k8s cluster.

**Describe the solution you'd like**
A helm chart :) 

**Describe alternatives you've considered**
Plain manifest files.

**Comment by BeyerJC** [comment]
What about this one  https://github.com/argoproj/argo-helm/tree/master/charts/argocd-image-updater

**Comment by 0m1xa** [comment]
@BeyerJC 
OMG... I didn't notice it.
Thank you :)

But nevertheless there is no mention in the [documentation](https://argocd-image-updater.readthedocs.io/en/stable/install/start/) about installation using helm chart.

**Comment by jannfis** [comment]
> There are offical charts for all argo products

The charts are not quite official. They are community maintained. But I agree, the chart could be mentioned in the installation guide. However, since I'm not involved in the creation and/or maintenance of the Chart and neither use it, I can't comment on its maturity.

Also, a good way to have customized installation manifests (without having to download and edit them manually) is
[kustomize](https://kustomize.io/)
