### ISSUE TITLE
Image Updater continuously force-pushes new commits when checkout branch is specified.

### ISSUE THREAD

**Issue by katainaka0503** [argoproj-labs/argocd-image-updater#895]
**Describe the bug**
After upgrading to v0.15.0, if `pushBranch` is not the same as `checkOutBranch` , argocd image updater continuously force pushes new commits.

**To Reproduce**
- Set `argocd-image-updater.argoproj.io/git-branch` to `:image-updater/master/account/{{range .Images}}{{.Name}}-{{.NewTag}}{{end}}`

**Expected behavior**
If there is no change, nothing is pushed.

**Additional context**

**Version**
After v0.15.0

**Logs**

**Comment by chengfang** [comment]
maybe related to the changes in PR https://github.com/argoproj-labs/argocd-image-updater/pull/882 to fix issues: https://github.com/argoproj-labs/argocd-image-updater/issues/673 https://github.com/argoproj-labs/argocd-image-updater/issues/879

**Comment by chengfang** [comment]
If the updates are the same as existing data, the git commit will be skipped. See https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/argocd/git.go#L284 and https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/argocd/git.go#L366 .  So it's a bit surprising to see pushing new commits with no changes.

**Comment by ixxeL2097** [comment]
same behaviour on my side, constantly pushes the same update. Very annoying cause it triggers pipeline each time argocd-image-updater pushes a new commit. Had to rollback to `v0.14.0`  for now

**Comment by chengfang** [comment]
I was able to reproduce it with this sample app https://github.com/chengfang/image-updater-examples/tree/main/push-branch-kustomize 

For each update cycle, it force-pushes the same update to the target branch, overwriting the previous update commit in the target git branch.

I think in v0.14.0, the same operation occurred too, but the push just failed to go through. In v0.15.0, with the additional --force option, these pushes succeeded.

With no new updates, the update cycle *should* skip git-commit or git-push steps. Will look into it  more.

**Comment by chengfang** [comment]
When using a custom write-back branch in the form of `checkoutBranch:pushBranch`, currently in each update cycle, we always create the `pushBranch` from `checkoutBranch`, and compare the potential update against the content in the newly created `pushBranch`, which is the same as `checkoutBranch`. This works fine if the write-back branch is for one off use for a specific tag of a specific image. But for a branch intended for multiple update cycles, the comparison always shows diff, because the new `pushBranch` based off `checkoutBranch` does not contain the latest image data.

One way to fix it is modify the current behaviro such that, if the `pushBranch` does not exist, we create a new `pushBranch` from `checkoutBranch`. If it always exists, I think we should honor it and checkout the `pushBranch` from origin, as opposed to creating a new branch from `checkoutBranch`, for all subsequent updates.  Any thoughts, concerns?
