### ISSUE TITLE
Unable to authenticate against private registry

### ISSUE THREAD

**Issue by jezumbro** [argoproj-labs/argocd-image-updater#90]
**Describe the bug**
When connecting to the registry the argo-image-updater is not authenticating against the server for the access token. Therefore when getting the new image the sever thinks the request is unauthorized and therefore cannot update the images.

**Additional context**
Tested using docker login with the credentials used for the k8s cluster and had no issues. 
Also validated that the associated .dockerconfigjson was able to login and pull images from the same registry with no issues. 
Have argocd and argocd-image-updater running in the cluster with the main dev repo, see attached config map for the argocd-image-updater-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  argo.server_addr: "argocd-server.argocd.svc.cluster.local"
  argocd.grpc_web: "true"
  argocd.insecure: "true"
  argocd.plaintext: "false"
  registries.conf: |
    registries:
    - name: my-registry
      api_url: https://<registry_name>
      ping: yes
      prefix: <registry_name>
      credentials: pullsecret:argocd-image-updater/regcred
---

**Version**
Image:         argoprojlabs/argocd-image-updater:latest

**Logs**
level=error msg="Could not get tags from registry: Get \"https://<private_registry>/v2/library/<image_name>/tags/list\": http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Class\\\":\\\"\\\",\\\"Name\\\":\\\"library/<image_name>\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")" alias=backend application=<argo_app>image_name=<image_name> image_tag=<image_tag> registry=<private_registry>
time="2020-09-22T18:51:20Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"

**Comment by jannfis** [comment]
Hey, I think the bug might not be related to  - From your logs, I see it tries to get tags for an image in `libary/<image_name>`, but I think this is erroneous. 

I believe this is due to a workaround in the code to work with Docker Hub registry, which uses a `library` namespace for non-canonical images (i.e. `nginx` is really `library/nginx` on Docker Hub). Is your target image specified without namespace? If so, can you try to put it in a dedicated namespace in your registry and see if that works?

**Comment by voglster** [comment]
We pulled from a dedicated namespace named library and it seems to work

**Comment by jannfis** [comment]
Ah, so that means that your image name is in fact `library/<image-name>`, and not just a flat `<image_name>`?

**Comment by jannfis** [comment]
Can you please try to configure the credentials on the image instead of per-registry, as described in https://argocd-image-updater.readthedocs.io/en/latest/configuration/images/#specifying-pull-secrets and see whether that works? 

I believe there might be a bug in per-registry configuration of credentials.

**Comment by jannfis** [comment]
Closing because I believe it's fixed by #91 

Feel free to reopen if the issue still persists.
